services:
    postgres:
      image: postgres:latest
      env_file:
        - .env.prod
      container_name: postgres
      restart: always
      command: -p 5432
#      expose:
#        - 5432
      ports:
        - 5432:5432
      volumes:
        - postgres:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  postgres: